### PR TITLE
Fix grid lines

### PR DESCRIPTION
**Pull request by kferris10**
Fix bug with the grid lines when no horizontal-minor grid lines where present.  [The updated tutorial](http://kferris10.github.io/animint/#scale_y_log10-and-geom_contour-with-stat_density2d) looks pretty good to me.

[There's still a problem](http://kferris10.github.io/animint/#geom_abline) with multiple ablines that I will fix momentarily.

### CODE REVIEW

**Comment by kferris10** [comment]
The parameters for grid lines and backgrounds/borders now inherit from `theme.pars$line` and `theme.pars$rect` respectively.  Combined with #97 this should close #89

**Comment by cpsievert** [comment]
The automatic pushing to gh-pages is not quite working yet, but I think we should merge +1 

(@kferris please update NEWS/DESCRIPTION and merge once @tdhock gives a +1)

**Comment by kferris10** [comment]
Got it. I think it should be ready to merge too if @tdhock does.

**Comment by tdhock** [comment]
+1

**Pull request merged**
