### PR TITLE
Non numeric updates

### PR DESCRIPTION
**Pull request by faizan-khan-iit**
For #174

### CODE REVIEW

**Comment by faizan-khan-iit** [comment]
@tdhock @cpsievert When I run the tests on my Windows machine I get this error:

```
library(animint)
library(testthat)
library(RSelenium)
setwd("./tests")
tests_init()
setwd("./testthat")
source("./helper-functions.R")
tests_run(filter = "renderer-4")
```
One of the errors:
```
[1] "geom_point_stroke"
1. Error: points are rendered with stroke-width (@test-renderer4-geom-point-stroke.R#15) -
could not find function "getNodeSet"
1: getStyleValue(info$html, "//g[@class=\"geom1_point_p1\"]//circle", "stroke-width") at testthat/test-renderer4-geom-point-stroke.R:15
```
which is the same as this error: https://travis-ci.org/tdhock/animint/jobs/182825914#L3100 that is encountered everywhere the function is used in the tests.
Any idea why this is happening? Could you verify this on your systems?

I know that the `getNodeSet` function belongs to the `XML` package, and loading the package (`library(XML)`) in the session seems to solve the problem.

I did not make any changes to the testing framework, so I guess it may be due to package updates.

**Comment by tdhock** [comment]
Hey Faizan thanks for the issue and PR. It seems totally reasonable to me to stop with an error when there is a non-numeric variable specified for axis updates. Maybe we need to add `library(XML)` to the testthat.R file?

**Comment by faizan-khan-iit** [comment]
Yeah that should do the trick. I will go ahead and try that.

**Comment by tdhock** [comment]
looks great, please merge, +1

**Comment by faizan-khan-iit** [comment]
Wercker seems to be a bit grumpy right now. The tests keep failing because it cannot download the required phantomjs: https://app.wercker.com/cpsievert/animint/runs/build/586d24f9bbb613010046ecf6?step=586d25414d45460001170acb

**Comment by tdhock** [comment]
its ok

**Pull request merged**
