### PR TITLE
Url fragment

### PR DESCRIPTION
**Pull request by viswaraavi**
The working example for the url_fragment_identifier is 
http://bl.ocks.org/viswaraavi/raw/ddc938aa4b74e21897686b64d195dc12/#sex_smoker={Female.No}

I thinks we need to change the url later to have {} because github is coverting to safe url

### CODE REVIEW

**Comment by viswaraavi** [comment]
The phantomjs is giving parse error I have to look at it if you have any idea can you suggest me.

**Comment by tdhock** [comment]
not sure about the phantomjs error, but maybe also try on your local machine using firefox? https://github.com/tdhock/animint/wiki/Testing

**Comment by viswaraavi** [comment]
is the feature Ok? Or do you think there has to be some changes. And also I think the java script file is becoming too big. So I think we have to seperate some of the functionality to other file

**Comment by viswaraavi** [comment]
I am closing this pull request and create a new one without previous commits. Sorry for the mess i have done

**Pull request closed without merging**
