### PR TITLE
Pirates example

### PR DESCRIPTION
**Pull request by kferris10**
Create a visualization of the pirates data and remove it from the TODO lists.

### CODE REVIEW

**Comment by cpsievert** [comment]
I wouldn't worry about the build failure. I think for the gist test to work properly, you'll need write access to this repo, so maybe @tdhock should grant you those permissions...

Did you look into using `geom_density2d()` as opposed to manually computing those bins and using `geom_tile()`?

**Comment by kferris10** [comment]
I did briefly, but I like the tiles better.

image

**Comment by cpsievert** [comment]
Oops, I meant `geom_bin2d()`, but I forgot that animint doesn't support it :(

```r
S <- matrix(c(1, .5, .5, 1), nrow = 2)
obs <- mvtnorm::rmvnorm(1000, sigma = S)
df <- setNames(data.frame(obs), c("var1", "var2"))
p <- ggplot(df, aes(var1, var2)) + geom_bin2d() +
  scale_fill_gradient(trans = "log")
animint2dir(list(p = p))
```

```r
 Error in saveLayer(L, df, meta) : 
  bin2d is not supported in animint. Try using geom_tile() and binning the data yourself.
```

This looks good to me, @tdhock go ahead and merge it you'd like

:+1:

**Comment by srvanderplas** [comment]
geom_density2d can be used with fill, if that helps. I agree about the
tiles, though - they seem to make a nicer visualization.

**Comment by kferris10** [comment]
I think the tiles look better too.  Thanks for your help!

**Comment by tdhock** [comment]
About the blue background, using a blue geom_rect is a clever workaround with the current code, but I would suggest this is a good time to actually implement that `theme` feature in animint. Basically that would mean (1) telling the compiler to extract the blue color from the theme element in `parsePlot`  https://github.com/tdhock/animint/blob/master/R/animint.R#L61 and then (2) tell the renderer to color the `<svg>` element, inside of `add_plot` https://github.com/tdhock/animint/blob/master/inst/htmljs/animint.js#L180

About the viz itself, I would suggest to add a second selection variable. For example, `geom_tile(aes(clickSelects=location))` in the second map, and then change the time series plot to `geom_line(aes(showSelected=location))` and use `selector.types=list(location=multiple)` ... this reminds me of a similar viz I did with some climate change data, see http://cbio.ensmp.fr/~thocking/animint-climate-change/index.html and source https://github.com/tdhock/climate-change/blob/master/figure-stations.R for possible inspiration.

**Comment by tdhock** [comment]
About computing your own `geom_tile` versus having ggplot2 compute `geom_density2d` etc, `geom_tile` is preferable if you want to use clickSelects in the tiles.

**Comment by tdhock** [comment]
I added @kferris10 as a collaborator with push access to tdhock/animint.

**Comment by kferris10** [comment]
Does that mean that I should just push the repository to tdhock/animint?  If so, to the master branch?

**Comment by tdhock** [comment]
in general you should try to avoid pushing to master if at all possible.

the better way to do it is to create a PR and then wait until you get comments and a +1 from either Carson or myself.

for this PR you already have Carson's +1, but you may want to address some of my comments, if you want to try to fix theme background colors, or try a re-design of the pirates viz with more interaction variables.

But it is fine if you don't want to do those extra things in this PR. In that case just push (to your kferris10:pirates_example branch) with a version update to NEWS (include a link to this PR) and DESCRIPTION, then click Merge pull request above.

**Comment by kferris10** [comment]
I think I'll take a stab at your suggestions today and tomorrow.  I'm going to close this PR and I'll open a new one when those updates are ready.

**Comment by tdhock** [comment]
if you end up pushing code to your kferris10:pirates_example branch then it is fine to re-open this same PR.

**Comment by kferris10** [comment]
I was planning to pushing it to tdhock:pirates_example to hopefully advoid any permission issues with the Travis tests.  Does that make sense?

**Comment by cpsievert** [comment]
Since your just adding an example here, I wouldn't worry about the tests. Do whatever is easiest for you.

**Comment by kferris10** [comment]
Okay, I'll just open this one back up.

@tdhock I'll work on your first suggestion (fixing the panel.background) and submit it as a separate PR.  For your second suggestion, I've updated [the visualization](http://bl.ocks.org/kferris10/raw/138c81b780fc13627548/).  I like your idea.  What do you think?

**Comment by tdhock** [comment]
Looks good! A few more suggestions:

Can you increase the default animation time delay? Personally I think it is
too fast and I interactively increased it to 1 second.

For the first map, can you color the dots by type of attack or some other
variable?

For the second couple of linked plots, the reader/user needs some way to
decode which lines correspond to which selected squares. One way to do that
would be to add a geom_text(aes(label=id, showSelected=id)) to both plots.

**Comment by kferris10** [comment]
[Updated link](http://bl.ocks.org/kferris10/raw/c68296a1e7b025611850/)

1.  I kind of like the faster animation.  I think that it makes it a little more interesting to view.

2. I don't think there's enough information available in the data to do much with the descriptions.  I haven't looked at them closely, but I think they are too specific to do much with.

3. Good call.  I also added clickSelects to the lines.

**Comment by tdhock** [comment]
ok, your call for the animation speed, no problem.

about the geom_text id labels, what you have is a good start. I think it
would be good to also try adding a black geom_text with the same id to the
map.

and I would add a geom_tallrect behind the second time series lines, or
maybe combine the two time series plots into a single facetted plot with
facet_grid(variable ~ ., scales="free") -- which would result in aligned x
axes (dates).

**Comment by kferris10** [comment]
[Updated link](http://bl.ocks.org/kferris10/raw/70d5ac0b1689d15c8abe/)

Thanks for your suggestions. I thought about adding the ids to the map, but I think it gets a bit noisy.  Especially if you select some tiles near each other, it gets hard to read pretty quickly.

**Comment by tdhock** [comment]
Thanks for your efforts Kevin. In terms of design this version looks best so far to me, even though the ids on the map can get a little busy. I think it is worth it to be able to quickly see the correspondence between the lines and the highlighed black squares.

Finally it seems like this viz reveals a bug in the animint.js renderer. After having already selected a few black squares on the second map, selecting a new year sometimes briefly moves the black square to an incorrect position. Do you see that too? or is it just on my web browser?

**Comment by tdhock** [comment]
the moving black squares is just a problem for me on firefox, not on chrome. so I guess we should not worry about this.

**Comment by kferris10** [comment]
Great! I won't have Wifi til Friday so I'll update this PR then

**Comment by kferris10** [comment]
[Updated visualization](http://bl.ocks.org/kferris10/raw/0b87a424fb2b2acc8bbf/)

I've gone back to the original code which uses `theme(panel.background = ...)` so this requires #78 to display the lightblue backgrounds.

**Comment by kferris10** [comment]
Is it okay if I go ahead and merge this example?

**Comment by tdhock** [comment]
Running your example code gave me

```
thocking@silene:~/R/animint-kferris10(pirates_example)$ Rscript inst/examples/pirates.R 
Loading required package: methods
Loading required package: proto

Attaching package: ‘dplyr’

The following object is masked from ‘package:stats’:

    filter

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in nrow(.) : object '.' not found
Calls: %>% ... mutate_ -> mutate_.tbl_df -> mutate_impl -> .Call -> nrow
Execution halted
```

**Comment by kferris10** [comment]
Hmmm...it works for me.  Is it possible that you are using an older version of `dplyr` or `magrittr`?

**Comment by tdhock** [comment]
You were right, I was in dependency hell! 

I finally got it to work with

```r
works_with_R("3.2.0",
             ggplot2="1.0.1",
             dplyr="0.4.2",
             tidyr="0.2.0.9000",
             maps="2.3.6",
             lubridate="1.3.3",
             stringr="0.6.2")
```

+1

**Pull request merged**
