### PR TITLE
fix common chunk bug

### PR DESCRIPTION
**Pull request by tdhock**
there is a new PeakConsistency data set, and a new test in test-PeakConsistency.R which fails. 

```
> library("testthat")

Attaching package: ‘testthat’

The following object is masked _by_ ‘.GlobalEnv’:

    watch

> library("animint")
Loading required package: proto
> library("RSelenium") # RSelenium works with firefox <= 37.0.2
Loading required package: RCurl
Loading required package: bitops
Loading required package: RJSONIO
Loading required package: XML

Attaching package: ‘XML’

The following object is masked _by_ ‘.GlobalEnv’:

    free

> tests_init("firefox")
Starting selenium binary. To shut it down, run: 
remDr$closeWindow() 
remDr$closeServer()
serving the directory /home/thocking/R/animint/tests/testthat at http://127.0.0.1:4848
> tests_run(filter="PeakConsistency")
1. Failure (at test-PeakConsistency.R#39): viz of just segments renders --------
length(line.list) not equal to 30
30 - 0 == 30

testthat results ================================================================
OK: 0 SKIPPED: 0 FAILED: 1
1. Failure (at test-PeakConsistency.R#39): viz of just segments renders 

Error: testthat unit tests failed
> 
```

The `geom_segment` rendering stops with an error in the JavaScript:

screenshot-varied-chunk-error

@caijun since this seems to be a bug in your varied/common chunk code, could you please take a look at fixing it when you get a chance?

### CODE REVIEW

**Comment by caijun** [comment]
OK, I will look at it and fix it.

**Comment by caijun** [comment]
Hi @tdhock ，I have a question about javascript to ask you. In following code, how can I get the value of `response`?

```
function wait() {
    if (g_info.download_status[g_info.common_tsv] != "saved") {
        setTimeout(wait, 5);
    } else {
        // copy data from common tsv to varied tsv
        var common_chunk = g_info.data[g_info.common_tsv];
        response = copy_chunk(common_chunk, response, g_info.columns.common);
    }
};
wait();
```

**Comment by tdhock** [comment]
do you want to look at the value of `response`? You could insert a Firebug breakpoint there to check its value in the debugger.

**Comment by caijun** [comment]
No, I would like to do some operations on variable `response` outside after function `wait()` changes the  value of variable `response`.

**Comment by tdhock** [comment]
well, response should be modified by wait so you should just be able to use it, e.g. 

```
var response = {}
function wait(key, val){
  response[key] = val;
}
wait("foo", "bar");
alert(response["foo"]);
```

**Comment by caijun** [comment]
I have drawn the figure, but the Panel 6~10 doesn't have geoms.

screen shot 2015-09-25 at 12 16 20

By checking data of Geoms from DOM, the data are existed. I don't know why they aren't drawn. @tdhock  could you have a look?

screen shot 2015-09-25 at 12 20 42

Following is the gist example.

http://bl.ocks.org/caijun/raw/7a4bda7b54a600a8b60f/

**Comment by tdhock** [comment]
Great job @caijun, that is the expected result! The first selection is sample.size=5 so it is expected that some panels should be empty.

**Comment by tdhock** [comment]
Before merging, I will write a few more tests in `test-PeakConsistency.R` based on that same data set.

**Comment by caijun** [comment]
The current `test-PeakConsistency.R` failed. Is it ok?

**Comment by tdhock** [comment]
I just tried your code on my local firefox, and `test-PeakConsistency.R` gives no errors.

**Comment by caijun** [comment]
OK, there may be something wrong with my test environment.

**Comment by tdhock** [comment]
The bigger data viz at the end of `test-PeakConsistency.R` is not rendering properly (there should be `geom_line` rendered as `<path>` elements in the first plot below)

screenshot-concat-not-a-fun

I will write a test.

**Comment by caijun** [comment]
Hi @tdhock, thank you for your `test-PeakConsistency.R`, which leads me to make the copy common chunk done before nest in the renderer. This largely simplify the code to save common chunk in the compiler and to copy common chunk in the renderer. Moreover, there is no need to save nest_order columns in both common chunk and varied chunks, which of course further optimizes the disk usage for animint and makes animint much efficient.

**Comment by tdhock** [comment]
Tests are passing on my machine, using firefox.

However something weird is going on with phantomjs. it passes when running just the "interactivity" tests:

```
> tests_init()
Starting phantomjs binary. To shut it down, run: 
 pJS$stop()
PhantomJS is launching GhostDriver...
[INFO  - 2015-09-28T18:55:12.740Z] GhostDriver - Main - running on port 4444
serving the directory /home/thocking/R/animint/tests/testthat at http://127.0.0.1:4848
tests_run(filter="interactivity")
[INFO  - 2015-09-28T18:55:26.709Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2015-09-28T18:55:26.709Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.customHeaders:  - {}
[INFO  - 2015-09-28T18:55:26.709Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-09-28T18:55:26.709Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5
> 
[1] "interactivity"
[ERROR - 2015-09-28T18:55:33.371Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - msg: TypeError: 'undefined' is not an object (evaluating 'd[a]')
[ERROR - 2015-09-28T18:55:33.371Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - stack:
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1006)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2229)
  d3_selection_each (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:1882)
  d3_transition_tween (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2232)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2094)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1332)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1634)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:850)
[ERROR - 2015-09-28T18:55:39.946Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - msg: TypeError: 'undefined' is not an object (evaluating 'd[a]')
[ERROR - 2015-09-28T18:55:39.946Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - stack:
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1006)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2229)
  d3_selection_each (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:1882)
  d3_transition_tween (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2232)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2094)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1332)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1634)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:850)
[1] "Interactive Legends"
[ERROR - 2015-09-28T18:55:59.873Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - msg: TypeError: 'undefined' is not an object (evaluating 's_info.type')
[ERROR - 2015-09-28T18:55:59.873Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - stack:
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1641)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1740)
  wrapper (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:1866)
testthat results ================================================================
OK: 54 SKIPPED: 0 FAILED: 0
>
```

but it stalls when running all tests (like on travis/wercker)

```
> tests_run()
[1] "aesthetics"
mapping: x = Sepal.Length, y = Petal.Length, showSelected = foo 
geom_point: na.rm = FALSE 
stat_identity:  
position_identity: (width = NULL, height = NULL)
$problem.aes
List of 1
 $ showSelected: symbol foo

$data.variables
[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"     

[1] "animation"
[INFO  - 2015-09-28T19:20:12.968Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[1] "One character value"
[1] "chunk vars"
[1] "coord"
[1] "facet-coord"
[1] "facet lines"
[1] "facet_grid(space=\"free\")"
[1] "facet-strips"
[1] "facet-trivial"
[1] "geom_abline"
[1] "geom line"
[1] "gists"
[1] "global variables"
[ERROR - 2015-09-28T19:21:50.817Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - msg: ReferenceError: Can't find variable: animint
[ERROR - 2015-09-28T19:21:50.817Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - stack:
  (anonymous function) (http://localhost:4848/animint-htmltest/:21)
[1] "hjust text anchor"
[1] 0.8
[1] "hline"
[1] "aes(href)"
[1] "HTML page title"
[1] "Interactive facets"
[1] "interactivity"
[ERROR - 2015-09-28T19:22:24.366Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - msg: TypeError: 'undefined' is not an object (evaluating 'd[a]')
[ERROR - 2015-09-28T19:22:24.366Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - stack:
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1006)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2229)
  d3_selection_each (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:1882)
  d3_transition_tween (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2232)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2094)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1332)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1634)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:850)
[ERROR - 2015-09-28T19:22:31.015Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - msg: TypeError: 'undefined' is not an object (evaluating 'd[a]')
[ERROR - 2015-09-28T19:22:31.015Z] Session [7b32a7f0-6612-11e5-93a1-ddbbd3e4dad5] - page.onError - stack:
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1006)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2229)
  d3_selection_each (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:1882)
  d3_transition_tween (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2232)
  (anonymous function) (http://localhost:4848/animint-htmltest/vendor/d3.v3.js:2094)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1332)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:1634)
  (anonymous function) (http://localhost:4848/animint-htmltest/animint.js:850)
[INFO  - 2015-09-28T19:25:13.051Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
```

**Comment by tdhock** [comment]
the phantomjs screenshot of the first viz in test-interactivity.R shows nothing on the second and third plots, which is not expected:

phantom-bug-screenshot

**Comment by caijun** [comment]
I also found the first viz in `test-interactivity.R` weird. When I used `animint2dir` to generate the first viz, the viz plots are as expected.

screen shot 2015-09-29 at 11 29 15

I don't know why the test failed.

**Comment by caijun** [comment]
Same problem is observed with PhantomJS on my Mac OS X.

**Pull request merged**
