### PR TITLE
Rotated axis labels

### PR DESCRIPTION
**Pull request by tdhock**
#37 reported that axis tick rotation does not work.

This is a first try to translate R/ggplot

```r
theme(axis.text.x=element_text(angle=70, hjust=1)) 
```

to HTML/SVG

```html
<text style="text-anchor: end;" transform="rotate(-70)">
```

So far I have just written renderer support for xangle and xanchor axis properties, so now we need to make the compiler output these values.

Also we need tests and compiler/renderer code for y axis angle rotation.

### CODE REVIEW

**Comment by tdhock** [comment]
Rotated x axis tick text should be working now. Next I will work on implementing the same functions for the y axis.

@mswastik can you please download the code and check if it works for your purposes?

```r
devtools::install_github("tdhock/animint@rotate")
```

**Comment by mswastik** [comment]
Thanks for adding the feature @tdhock the texts are rotated now...but as you can see in the image texts are cutoff due to limited space available for them and x-axis label name did not shifted downward. I think some final adjustments are needed.
image

**Comment by tdhock** [comment]
Thanks for the revealing screenshot! I guess we will need to add some JavaScript code that adjusts the axis margin size in function of the tick text size. @cpsievert implemented some related code with facet margin sizes recently, do you have any ideas about how to do that?

**Comment by cpsievert** [comment]
[Here](https://github.com/cpsievert/animint/blob/master/inst/htmljs/animint.js#L137-142) is the snippet where we measure the amount of padding to add for x/y tick labels. The problem seems to be due to the fact that `measureText()` assumes that the text is at an angle of 0, 90, 180, ...

I'm not immediately sure how to modify `measureText()` to support this feature. Any ideas @srvanderplas?

**Comment by srvanderplas** [comment]
Trig? If you specify the angle, you should be able to get a relatively
decent measure of height and width offset from the plot. Obviously there
will be some nesting issues with the width, but I think it should be fairly
easy to deal with that by only considering the edge cases.

**Comment by cpsievert** [comment]
I'd like to avoid doing unnecessary math, if possible :P

The [getBBox](http://stackoverflow.com/questions/1636842/svg-text-element-width?rq=1) method looks promising, but we'd have to measure SVG elements as opposed to HTML. This should also have the added benefit of avoiding creation of hidden elements.

**Comment by cpsievert** [comment]
@tdhock would you like me to take a stab at re-implementing `measureText()` to use `getBBox()`? I'm thinking it'd be nice to have measureText() take on a css selector to select (existing text) elements and return {height: num, width: num}

**Comment by srvanderplas** [comment]
Sounds like that investment might also pay off if we wanted to fix things
ggplot2 doesn't do that well (expanding axes to accommodate text labels,
etc.)

**Comment by tdhock** [comment]
Yes please go ahead and try to re-implement measureText, and push commits to rotate branch.

**Comment by tdhock** [comment]
And I guess we should add a test for axes labels not overlapping tick labels, but that seems complicated.

**Comment by cpsievert** [comment]
The following code gives me [this](http://bl.ocks.org/cpsievert/062c9c578519cc1f48a6) now.

```s
library(animint)
mtcars$vs <- paste("Some really long label text", mtcars$vs)

p <- qplot(data = mtcars, vs, wt, geom = "point") +
  facet_wrap(~am) +
  theme(axis.text.x = element_text(angle=70, hjust=1)) 

animint2gist(list(plot = p))
```

Let me know if any ideas for more tests

**Comment by tdhock** [comment]
I used Selenium's getLocation and getSize methods to implement a test to make sure tick text does not overlap x axis title.

http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/WebElement.html#getLocation%28%29

**Comment by cpsievert** [comment]
@tdhock I like the tests you have here. You have my approval to merge. Please update DESCRIPTION/NEWS accordingly :)

**Pull request merged**
